version: 2
updates:
  # glean
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 8
    versioning-strategy: lockfile-only

  # glean-python
  - package-ecosystem: "pip"
    directory: "/glean-core/python"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 8
    ignore:
      # Updated in lockstep across all implementations
      - dependency-name: "glean_parser"
