[book]
title = "Glean SDKs - Cross-platform Telemetry Libraries"
authors = ["Glean Team"]
src = "."

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["../shared/glean.css", "../shared/mermaid.css"]
additional-js = ["../shared/tabs.js", "../shared/label-check.js", "../shared/mermaid.min.js", "../shared/mermaid-init.js", "chart.min.js", "chart-distributions.js", "chart-distributions-ui.js"]
git-repository-url = "https://github.com/mozilla/glean"
git-branch = "main"
mathjax-support = true

[output.html.fold]
enable = true
level = 0

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
