
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.glean]
audit-as-crates-io = false

[policy.glean-core]
audit-as-crates-io = false

[policy.sample]
audit-as-crates-io = false

[[exemptions.android_log-sys]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "1.3.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.19"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "4.0.2"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.fs-err]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.goblin]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.5.6"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-run"

[[exemptions.json-pointer]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.139"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.oslog]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-run"

[[exemptions.scroll]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.scroll_derive]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.10"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.xshell]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.xshell-macros]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.xshell-venv]]
version = "1.1.0"
criteria = "safe-to-deploy"
